name: Generate Android APK

on:
  push:
    branches: [ "main", "master" ]

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up JDK 17
          uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: '17'

        - name: Build WebAPK via PWABuilder Action
          uses: PWABuilder/pwabuilder-android-action@main
          with:
            manifest-url: 'https://raw.githubusercontent.com/${{ github.repository }}/main/manifest.json'
            name: 'Tasbeeh Pro'
            icon-url: 'https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/icon.png'
            package-id: 'com.tasbeeh.pro'

